config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'profiles#home'
  get "profiles/about" => "profiles#about"
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :stories
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
    has_one :user
end

app/models/story.rb
class Story < ApplicationRecord
    validates :title, presence: true
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                format: { with: VALID_EMAIL_REGEX },
                uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
    has_many :stories, dependent: :destroy
    
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
        SecureRandom.urlsafe_base64
    end

    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
        update_attribute(:remember_digest, nil)
    end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'メールアドレスかパスワードが間違っています。'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @story = Story.all
  end

  def new
    @story = Story.new
  end

  def create 
    @story = Story.new(stories_params)
    respond_to do |format|
      if @story.save
        format.html { redirect_to stories_path, notice: '新規作成が行なわれました'}
        log_in @user
        redirect_to @user
      else
        format.html {render 'new'}
      end
    end
  end
  

  def edit
    @story = Story.find(params[:id])
  end

  def update
    @story = Story.find(params[:id])
      if @story.update(stories_params)
        flash[:notice]= "「#{@story.title}」をかえたよ"
        redirect_to stories_path
      else
        render 'edit'
      end
  end


  def show
    @story= Story.find(params[:id])
  end

  def destroy
    respond_to do |format|
      @story = Story.find(params[:id])
      @story.destroy
    end
  end

  private
  def stories_params
    params.require(:story).permit(:title, :first, :second, :third, :last)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy] 
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy
  
  def new
    @user = User.new
  end

  def index 
    @users = User.all.page(params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save 
      flash[:success] = "Welcome to My stories!"
      log_in @user
      redirect_back_or @user
    else
      render 'new'
    end
  end
  

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "変更しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインしてください"
        redirect_to login_url
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end


    def remember(user)
        user.remember
        cookies.permanent.signed[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.signed[:user_id])
            user = User.find_by(id: user_id)
            if user && user.authenticated?(cookies[:remember_token])
                log_in user
                @current_user = user
            end
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def current_user?(user)
        user == current_user
    end

    def forget(user)
        user.forget
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end

    def log_out
        forget(current_user)
        session.delete(:user_id)
        @current_user = nil
    end

    def redirect_back_or(default)
        redirect_to(session[:forwarding_url] || default)
        session.delete(:forwarding_url)
    end

    # アクセスしようとしたURLを覚えておく
    def store_location
        session[:forwarding_url] = request.original_url if request.get?
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_header.html.slim
 header.navbar.navbar-fixed-top.navbar-inverse
    .container
      = link_to "My stories", root_path, id: "logo"
      nav
        ul.nav.navbar-nav.navbar-right
          li= link_to_unless_current "ホーム", root_path 
          li= link_to_unless_current "ヘルプ", profiles_about_path
          - if logged_in?
            li= link_to "私のお話", '#'
            li= link_to "ユーザー一覧", users_path
            li= link_to "プロフィール", current_user
            li= link_to "登録情報変更", edit_user_path(current_user)
            li= link_to "ログアウト", logout_path, method: :delete
          - else
            li= link_to "ログイン", login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Syousetsu
    = csrf_meta_tags
    = csp_meta_tag

    link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"
      = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
      = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

      script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" 
      link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" rel="stylesheet"
  body
    = render partial: 'layouts/header'

    - flash.each do |message_type, message|
      div class=("alert alert-#{message_type}") = message  
    = yield

app/views/profiles/about.html.slim
h1 お話を作ろう
p ここでは、起承転結からなるお話を書いたり、他の人が作ったお話を見たり、自分のお話を見せたりできます。

app/views/profiles/home.html.slim
h1 お話を作ろう！
p 自分だけのお話を作ってみんなとシェアしませんか？

app/views/shared/_error_messages.html.slim
- if @user.errors.any?
  #error_explanation
    .alert.alert-danger
      | The form contains #{pluralize(@user.errors.count, "error")}.
    ul
      - @user.errors.full_messages.each do |msg|
        li= msg

app/views/stories/edit.html.slim
- if @story.errors
  .ul
    - @story.errors.full_messages.each do |msg|
          = msg

h1 お話をかえる

= link_to "もどる", stories_path

= form_with model: @story, local: true do |f|
    .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', size:80
    .form-group
        = f.label :first
        = f.text_area :first, class: 'form-control',size:"50x10"
    .form-group
        = f.label :second
        = f.text_area :second, class: 'form-control',size:"50x10"
    .form-group
        = f.label :third
        = f.text_area :third, class: 'form-control',size:"50x10"
    .form-group
        = f.label :last
        = f.text_area :last, class: 'form-control',size:"50x10"
    = f.submit 'かえる', class: 'btn btn-primary'
  

app/views/stories/index.html.slim
h1 私のお話

= link_to "つくる", new_story_path, class: 'btn btn-info'

table.table.table-hover
  thead
    tr
      th = Story.human_attribute_name (:title)
      th = Story.human_attribute_name (:created_at)
      th
      th
      th
  tbody
    - @story.each do |story|
      tr style= "background-color: #{cycle('#FFffFF','#FFff99')}"
        td = story.title
        td = story.created_at
        td = link_to "かえる", edit_story_path(story.id), class: 'btn btn-primary'
        td = link_to "みる", story_path(story.id), class: 'btn btn-success'
        td = link_to "けす", story_path(story.id), method: :delete, class: 'btn btn-danger', data: { confirm: "本当に削除しますか？" }


    

app/views/stories/new.html.slim
- if @story.errors
  .ul
    - @story.errors.full_messages.each do |msg|
          = msg

h1 新しいお話

= form_with model: @story, local: true do |f|
    .form-group
        = f.label :title
        = f.text_field :title, class: 'form-control', size:80
    .form-group
        = f.label :first
        = f.text_area :first, class: 'form-control',size:"50x10"
    .form-group
        = f.label :second
        = f.text_area :second, class: 'form-control',size:"50x10"
    .form-group
        = f.label :third
        = f.text_area :third, class: 'form-control',size:"50x10"
    .form-group
        = f.label :last
        = f.text_area :last, class: 'form-control',size:"50x10"
    = f.submit 'つくる', class: 'btn btn-info'

app/views/stories/show.html.slim
h1 = @story.title

= link_to "もどる", stories_path
table.table.table-hover
  tbody
    tr
      th = Story.human_attribute_name(:first)
      td = @story.first
    tr
      th = Story.human_attribute_name(:second)
      td = @story.second
    tr
      th = Story.human_attribute_name(:third)
      td = @story.third
    tr
      th = Story.human_attribute_name(:last)
      td = @story.last

= link_to "かえる", edit_story_path(@story.id), class: 'btn btn-primary'
= link_to "けす", story_path(@story.id), method: :delete, class: 'btn btn-danger',  data: { confirm: "本当に削除しますか？" }

app/views/users/edit.html.slim
- provide(:title, "Edit user")
h1 登録情報変更
.row
  .col-md-6.col-md-offset-3

= form_for(@user) do |f|
    = render 'shared/error_messages', object: @user
    = f.label :name
    = f.text_field :name, class: 'form-control'

    = f.label :email
    = f.email_field :email, class: 'form-control'

    = f.label :password
    = f.password_field :password, class: 'form-control'

    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'

    = f.submit "登録内容を変更する", class: "btn btn-primary"

    
    .gravatar_edit
      = gravatar_for @user
      a href="http://gravatar.com/emails" target="_blank"  change

app/views/users/index.html.slim
- provide(:title, 'All users')
h1 ユーザー一覧

ul.users
  - @users.each do |user|
    li
      = gravatar_for user, size: 50
      = link_to user.name, user
      - if current_user.admin? && !current_user?(user)
        |  | 
        = link_to "delete", user, method: :delete, data: { confirm: "本当に消しますか?" }                                 
= paginate @users

app/views/users/new.html.slim
- provide(:title, 'Signup')
h1 signup
.row
  .col-md-6.col-md-offset-3
    =form_for(@user, url: signup_path) do |f|
      = render 'shared/error_messages'

      = f.label :name
      = f.text_field :name, class: 'form-control' 

      = f.label :email
      = f.email_field :email, class: 'form-control' 

      = f.label :password
      = f.password_field :password, class: 'form-control' 

      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: 'form-control' 

      =f.submit "とうろくする",  class: "btn btn-primary"

app/views/users/show.html.slim
- provide(:title, @user.name)
.row
  aside.col-md-4
    section.user-info
      h1
        = gravatar_for @user
        = @user.name